/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as BriefsRouteImport } from './routes/briefs'
import { Route as CommsRouteImport } from './routes/comms'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as GuardrailsRouteImport } from './routes/guardrails'
import { Route as PlannerRouteImport } from './routes/planner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsRoute = BriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommsRoute = CommsRouteImport.update({
  id: '/comms',
  path: '/comms',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardrailsRoute = GuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/briefs': typeof BriefsRoute
  '/comms': typeof CommsRoute
  '/daily': typeof DailyRoute
  '/guardrails': typeof GuardrailsRoute
  '/planner': typeof PlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/briefs': typeof BriefsRoute
  '/comms': typeof CommsRoute
  '/daily': typeof DailyRoute
  '/guardrails': typeof GuardrailsRoute
  '/planner': typeof PlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/briefs': typeof BriefsRoute
  '/comms': typeof CommsRoute
  '/daily': typeof DailyRoute
  '/guardrails': typeof GuardrailsRoute
  '/planner': typeof PlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefing'
    | '/briefs'
    | '/comms'
    | '/daily'
    | '/guardrails'
    | '/planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefing'
    | '/briefs'
    | '/comms'
    | '/daily'
    | '/guardrails'
    | '/planner'
  id:
    | '__root__'
    | '/'
    | '/briefing'
    | '/briefs'
    | '/comms'
    | '/daily'
    | '/guardrails'
    | '/planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingRoute: typeof BriefingRoute
  BriefsRoute: typeof BriefsRoute
  CommsRoute: typeof CommsRoute
  DailyRoute: typeof DailyRoute
  GuardrailsRoute: typeof GuardrailsRoute
  PlannerRoute: typeof PlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs': {
      id: '/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof BriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comms': {
      id: '/comms'
      path: '/comms'
      fullPath: '/comms'
      preLoaderRoute: typeof CommsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardrails': {
      id: '/guardrails'
      path: '/guardrails'
      fullPath: '/guardrails'
      preLoaderRoute: typeof GuardrailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingRoute: BriefingRoute,
  BriefsRoute: BriefsRoute,
  CommsRoute: CommsRoute,
  DailyRoute: DailyRoute,
  GuardrailsRoute: GuardrailsRoute,
  PlannerRoute: PlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
